# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: c950e65e0e7df75840f2481d4d5bcccec7d3961339762a2da7adaa2de5a62fd30e4d4b30b2e8e16d54f889a4daca25fc994bfc45d20dd7ecbde50e6eda2248a5

test:
  secret_key_base: dabf07d5daf10ba9d3e28995189bd3ec89c2576f27f8faeff7cab5a27a1141f2db62d6dd9c045f82ade165e6ebaf7fe4b69b264d366914415040bec746fbda27

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
